name: shout_board
description: "A digital board to shout messages."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^2.4.4
  go_router: ^14.7.2
  logging: ^1.3.0
  marqueer: ^2.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
